# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dashboard(object):
    def setupUi(self, Dashboard):
        Dashboard.setObjectName("Dashboard")
        Dashboard.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dashboard)
        self.verticalLayout.setObjectName("verticalLayout")
        self.summaryWidget = QtWidgets.QWidget(Dashboard)
        self.summaryWidget.setObjectName("summaryWidget")
        self.summaryLayout = QtWidgets.QHBoxLayout(self.summaryWidget)
        self.summaryLayout.setObjectName("summaryLayout")
        self.totalTasks = QtWidgets.QLabel(self.summaryWidget)
        self.totalTasks.setObjectName("totalTasks")
        self.summaryLayout.addWidget(self.totalTasks)
        self.completedTasks = QtWidgets.QLabel(self.summaryWidget)
        self.completedTasks.setObjectName("completedTasks")
        self.summaryLayout.addWidget(self.completedTasks)
        self.remainingTasks = QtWidgets.QLabel(self.summaryWidget)
        self.remainingTasks.setObjectName("remainingTasks")
        self.summaryLayout.addWidget(self.remainingTasks)
        self.verticalLayout.addWidget(self.summaryWidget)
        self.searchBar = QtWidgets.QLineEdit(Dashboard)
        self.searchBar.setObjectName("searchBar")
        self.verticalLayout.addWidget(self.searchBar)
        self.filterWidget = QtWidgets.QWidget(Dashboard)
        self.filterWidget.setObjectName("filterWidget")
        self.filterLayout = QtWidgets.QHBoxLayout(self.filterWidget)
        self.filterLayout.setObjectName("filterLayout")
        self.filterComboBox = QtWidgets.QComboBox(self.filterWidget)
        self.filterComboBox.setObjectName("filterComboBox")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.filterLayout.addWidget(self.filterComboBox)
        self.refreshButton = QtWidgets.QPushButton(self.filterWidget)
        self.refreshButton.setObjectName("refreshButton")
        self.filterLayout.addWidget(self.refreshButton)
        self.verticalLayout.addWidget(self.filterWidget)
        self.progressBar = QtWidgets.QProgressBar(Dashboard)
        self.progressBar.setProperty("value", 50)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.todoTable = QtWidgets.QTableWidget(Dashboard)
        self.todoTable.setObjectName("todoTable")
        self.todoTable.setColumnCount(5)
        self.todoTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.todoTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todoTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.todoTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.todoTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.todoTable.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.todoTable)
        self.tabWidget = QtWidgets.QTabWidget(Dashboard)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonWidget = QtWidgets.QWidget(Dashboard)
        self.buttonWidget.setObjectName("buttonWidget")
        self.buttonLayout = QtWidgets.QHBoxLayout(self.buttonWidget)
        self.buttonLayout.setObjectName("buttonLayout")
        self.addButton = QtWidgets.QPushButton(self.buttonWidget)
        self.addButton.setObjectName("addButton")
        self.buttonLayout.addWidget(self.addButton)
        self.editButton = QtWidgets.QPushButton(self.buttonWidget)
        self.editButton.setStyleSheet("\n"
"          QPushButton {\n"
"              background-color: rgb(255, 85, 0);\n"
"              color: white;\n"
"              border: none;\n"
"              border-radius: 5px;\n"
"              padding: 5px 10px;\n"
"          }\n"
"          QPushButton:hover {\n"
"              background-color: #e0a800;\n"
"          }\n"
"         ")
        self.editButton.setObjectName("editButton")
        self.buttonLayout.addWidget(self.editButton)
        self.deleteButton = QtWidgets.QPushButton(self.buttonWidget)
        self.deleteButton.setObjectName("deleteButton")
        self.buttonLayout.addWidget(self.deleteButton)
        self.verticalLayout.addWidget(self.buttonWidget)
        self.backButton = QtWidgets.QPushButton(Dashboard)
        self.backButton.setObjectName("backButton")
        self.verticalLayout.addWidget(self.backButton)

        self.retranslateUi(Dashboard)
        QtCore.QMetaObject.connectSlotsByName(Dashboard)

    def retranslateUi(self, Dashboard):
        _translate = QtCore.QCoreApplication.translate
        Dashboard.setWindowTitle(_translate("Dashboard", "Dashboard"))
        Dashboard.setStyleSheet(_translate("Dashboard", "\n"
"    QWidget {\n"
"        background-color: #f7f7f7;\n"
"    }\n"
"   "))
        self.totalTasks.setStyleSheet(_translate("Dashboard", "\n"
"          QLabel {\n"
"              font-weight: bold;\n"
"              color: #4CAF50;\n"
"          }\n"
"         "))
        self.totalTasks.setText(_translate("Dashboard", "Total Tasks: 10"))
        self.completedTasks.setStyleSheet(_translate("Dashboard", "\n"
"          QLabel {\n"
"              font-weight: bold;\n"
"              color: #007BFF;\n"
"          }\n"
"         "))
        self.completedTasks.setText(_translate("Dashboard", "Completed: 5"))
        self.remainingTasks.setStyleSheet(_translate("Dashboard", "\n"
"          QLabel {\n"
"              font-weight: bold;\n"
"              color: #FFC107;\n"
"          }\n"
"         "))
        self.remainingTasks.setText(_translate("Dashboard", "Remaining: 5"))
        self.searchBar.setStyleSheet(_translate("Dashboard", "\n"
"       QLineEdit {\n"
"           border: 1px solid #ccc;\n"
"           border-radius: 5px;\n"
"           padding: 5px;\n"
"           background-color: #ffffff;\n"
"       }\n"
"      "))
        self.searchBar.setPlaceholderText(_translate("Dashboard", "Search tasks..."))
        self.filterComboBox.setStyleSheet(_translate("Dashboard", "\n"
"          QComboBox {\n"
"              border: 1px solid #ccc;\n"
"              border-radius: 5px;\n"
"              padding: 3px;\n"
"              background-color: #ffffff;\n"
"          }\n"
"         "))
        self.filterComboBox.setCurrentText(_translate("Dashboard", "-Filter-"))
        self.filterComboBox.setItemText(0, _translate("Dashboard", "Personal"))
        self.filterComboBox.setItemText(1, _translate("Dashboard", "Team"))
        self.filterComboBox.setItemText(2, _translate("Dashboard", "Deadline Today"))
        self.filterComboBox.setItemText(3, _translate("Dashboard", "In Progress"))
        self.filterComboBox.setItemText(4, _translate("Dashboard", "Complete"))
        self.filterComboBox.setItemText(5, _translate("Dashboard", "Incomplete"))
        self.refreshButton.setStyleSheet(_translate("Dashboard", "\n"
"          QPushButton {\n"
"              background-color: #4CAF50;\n"
"              color: white;\n"
"              border: none;\n"
"              border-radius: 5px;\n"
"              padding: 5px 10px;\n"
"          }\n"
"          QPushButton:hover {\n"
"              background-color: #45a049;\n"
"          }\n"
"         "))
        self.refreshButton.setText(_translate("Dashboard", "Refresh"))
        self.progressBar.setStyleSheet(_translate("Dashboard", "\n"
"       QProgressBar {\n"
"           border: 1px solid #ccc;\n"
"           border-radius: 5px;\n"
"           background: #f3f3f3;\n"
"       }\n"
"       QProgressBar::chunk {\n"
"           background-color: #4CAF50;\n"
"           width: 20px;\n"
"       }\n"
"      "))
        self.todoTable.setStyleSheet(_translate("Dashboard", "\n"
"       QTableWidget {\n"
"           background-color: #ffffff;\n"
"           border: 1px solid #ccc;\n"
"           border-radius: 5px;\n"
"       }\n"
"       QHeaderView::section {\n"
"           background-color: #4CAF50;\n"
"           color: white;\n"
"           padding: 4px;\n"
"           font-weight: bold;\n"
"       }\n"
"      "))
        item = self.todoTable.horizontalHeaderItem(0)
        item.setText(_translate("Dashboard", "Title"))
        item = self.todoTable.horizontalHeaderItem(1)
        item.setText(_translate("Dashboard", "Description"))
        item = self.todoTable.horizontalHeaderItem(2)
        item.setText(_translate("Dashboard", "Status"))
        item = self.todoTable.horizontalHeaderItem(3)
        item.setText(_translate("Dashboard", "Type"))
        item = self.todoTable.horizontalHeaderItem(4)
        item.setText(_translate("Dashboard", "Priority"))
        self.addButton.setStyleSheet(_translate("Dashboard", "\n"
"          QPushButton {\n"
"              background-color: #007BFF;\n"
"              color: white;\n"
"              border: none;\n"
"              border-radius: 5px;\n"
"              padding: 5px 10px;\n"
"          }\n"
"          QPushButton:hover {\n"
"              background-color: #0056b3;\n"
"          }\n"
"         "))
        self.addButton.setText(_translate("Dashboard", "Add"))
        self.editButton.setText(_translate("Dashboard", "Edit"))
        self.deleteButton.setStyleSheet(_translate("Dashboard", "\n"
"          QPushButton {\n"
"              background-color: #DC3545;\n"
"              color: white;\n"
"              border: none;\n"
"              border-radius: 5px;\n"
"              padding: 5px 10px;\n"
"          }\n"
"          QPushButton:hover {\n"
"              background-color: #c82333;\n"
"          }\n"
"         "))
        self.deleteButton.setText(_translate("Dashboard", "Delete"))
        self.backButton.setStyleSheet(_translate("Dashboard", "\n"
"       QPushButton {\n"
"           background-color: #6c757d;\n"
"           color: white;\n"
"           border: none;\n"
"           border-radius: 5px;\n"
"           padding: 5px 10px;\n"
"       }\n"
"       QPushButton:hover {\n"
"           background-color: #5a6268;\n"
"       }\n"
"      "))
        self.backButton.setText(_translate("Dashboard", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dashboard = QtWidgets.QWidget()
    ui = Ui_Dashboard()
    ui.setupUi(Dashboard)
    Dashboard.show()
    sys.exit(app.exec_())
