# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_confirm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteConfirmDialog(object):
    def setupUi(self, DeleteConfirmDialog):
        DeleteConfirmDialog.setObjectName("DeleteConfirmDialog")
        DeleteConfirmDialog.resize(300, 150)
        self.verticalLayout = QtWidgets.QVBoxLayout(DeleteConfirmDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.confirmLabel = QtWidgets.QLabel(DeleteConfirmDialog)
        self.confirmLabel.setObjectName("confirmLabel")
        self.verticalLayout.addWidget(self.confirmLabel)
        self.buttonWidget = QtWidgets.QWidget(DeleteConfirmDialog)
        self.buttonWidget.setObjectName("buttonWidget")
        self.buttonLayout = QtWidgets.QHBoxLayout(self.buttonWidget)
        self.buttonLayout.setObjectName("buttonLayout")
        self.yesButton = QtWidgets.QPushButton(self.buttonWidget)
        self.yesButton.setObjectName("yesButton")
        self.buttonLayout.addWidget(self.yesButton)
        self.noButton = QtWidgets.QPushButton(self.buttonWidget)
        self.noButton.setObjectName("noButton")
        self.buttonLayout.addWidget(self.noButton)
        self.verticalLayout.addWidget(self.buttonWidget)

        self.retranslateUi(DeleteConfirmDialog)
        QtCore.QMetaObject.connectSlotsByName(DeleteConfirmDialog)

    def retranslateUi(self, DeleteConfirmDialog):
        _translate = QtCore.QCoreApplication.translate
        DeleteConfirmDialog.setWindowTitle(_translate("DeleteConfirmDialog", "Confirm Delete"))
        self.confirmLabel.setText(_translate("DeleteConfirmDialog", "Are you sure you want to delete this task?"))
        self.yesButton.setText(_translate("DeleteConfirmDialog", "Yes"))
        self.noButton.setText(_translate("DeleteConfirmDialog", "No"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DeleteConfirmDialog = QtWidgets.QDialog()
    ui = Ui_DeleteConfirmDialog()
    ui.setupUi(DeleteConfirmDialog)
    DeleteConfirmDialog.show()
    sys.exit(app.exec_())
